# Generated by Django 6.0 on 2025-12-11 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(help_text='The group the user is requesting to join.', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='accounts.savingsgroup')),
                ('handled_by', models.ForeignKey(blank=True, help_text='The admin who handled this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user requesting to join.', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Join Request',
                'verbose_name_plural': 'Group Join Requests',
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(help_text='The group the user is a member of.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.savingsgroup')),
                ('user', models.ForeignKey(help_text='The active member.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
