# Generated by Django 6.0 on 2025-12-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupjoinrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Optional reason provided by the user for wanting to join the group.', null=True),
        ),
    ]
