# Generated by Django 6.0 on 2026-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Links related entries for double-entry integrity. Null for external inflows/outflows.', null=True),
        ),
    ]
