# Generated by Django 5.1.3 on 2025-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Cloudinary URL of profile picture', max_length=500, null=True),
        ),
    ]
