# Generated by Django 5.1.3 on 2025-12-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Profile Picture URL'),
        ),
    ]
