# Generated by Django 6.0 on 2026-01-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_idempotencykey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgroup',
            name='current_cycle_number',
            field=models.PositiveIntegerField(default=1, help_text='The actual cycle the group is in. Incremented manually on payout.'),
        ),
    ]
