# Generated by Django 6.0 on 2026-01-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_savingsgroup_current_cycle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(help_text='The group the user is a member of.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.savingsgroup'),
        ),
    ]
